using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace InterceptorFramework;

[Generator]
public class InterceptorSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "Generators";
    private const string AttributeName = "InterceptorAttribute";

    private const string AttributeSourceCode =
        // lang=CSharp
        $$"""
          // <auto-generated/>
          namespace {{Namespace}}
          {
              [System.AttributeUsage(System.AttributeTargets.Method)]
              public class {{AttributeName}}<T> : System.Attribute
              {
                  public string Value { get; }
                  public {{AttributeName}}(string value) => Value = value;
              }
              
              [System.AttributeUsage(System.AttributeTargets.Method)]
              public class {{AttributeName}} : System.Attribute
              {
                  public string Value { get; }
                  public {{AttributeName}}(System.Type type, string methodName) => Value = methodName;
              }
          }
          namespace System.Runtime.CompilerServices
          {
              [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
              public sealed class InterceptsLocationAttribute(string filePath, int line, int column) : Attribute;
          }
          """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "ReportAttribute.g.cs",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        var interceptingInvocationsProvider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is InvocationExpressionSyntax
                {
                    Expression: MemberAccessExpressionSyntax
                },
                transform: (GeneratorSyntaxContext context, CancellationToken token) =>
                {
                    var interceptableLocation =
                        context.SemanticModel.GetInterceptableLocation((InvocationExpressionSyntax)context.Node);
                    if (interceptableLocation is null)
                    {
                        throw new Exception("Bug");
                        // generator wants to intercept call, but host thinks call is not interceptable. bug.
                    }

                    // generator is careful to propagate only equatable data (i.e., not syntax nodes or symbols).
                    return (invocationExpression: (InvocationExpressionSyntax)context.Node, interceptableLocation);
                })
            .Collect();

        var interceptorDeclarationProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is MethodDeclarationSyntax { },
                (ctx, _) => GetMethodForSourceGen(ctx))
            .Where(t => t.attributeFound)
            .Select((m, ct) => m.method)
            .Combine(interceptingInvocationsProvider)
            .Select((t, ct) =>
            {
                var (interceptor, interceptions) = t;
                var candidates =
                    interceptions
                        .Where(i =>
                        {
                            var accessExpressionSyntax =
                                (MemberAccessExpressionSyntax)i.invocationExpression.Expression;

                            return i.invocationExpression.ArgumentList.Arguments.Count ==
                                   interceptor.ParameterList.Parameters.Count &&
                                   accessExpressionSyntax.Name.ToString() == interceptor.Identifier.Text;
                        })
                        .ToImmutableArray();
                return (interceptor, candidates);
            });


        context.RegisterSourceOutput(context.CompilationProvider.Combine(interceptorDeclarationProvider.Collect()),
            (ctx, t) => GenerateCode(ctx, t.Left, t.Right));
    }

    private (MethodDeclarationSyntax method, bool attributeFound) GetMethodForSourceGen(GeneratorSyntaxContext context)
    {
        var classDeclarationSyntax = (MethodDeclarationSyntax)context.Node;

        // Go through all attributes of the class.
        foreach (AttributeListSyntax attributeListSyntax in classDeclarationSyntax.AttributeLists)
        foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                continue; // if we can't get the symbol, ignore it

            string attributeName = attributeSymbol.ContainingType.ToDisplayString();

            // Check the full name of the [Report] attribute.
            if (attributeName == $"{Namespace}.{AttributeName}")
            {
                return (classDeclarationSyntax, true);
            }
        }

        return (classDeclarationSyntax, false);
    }

    private void GenerateCode(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<(MethodDeclarationSyntax interceptor, ImmutableArray<(InvocationExpressionSyntax invocation,
            InterceptableLocation interceptableLocation)> candidates)> interceptorMethods)
    {
        foreach (var (interceptor, candidates) in interceptorMethods)
        {
            var semanticModel = compilation.GetSemanticModel(interceptor.SyntaxTree);

            if (ModelExtensions.GetDeclaredSymbol(semanticModel, interceptor) is not IMethodSymbol
                interceptionMethodSymbol)
            {
                continue;
            }

            var interceptorParameterTypes = interceptionMethodSymbol.Parameters.Select(t => t.Type).ToImmutableArray();
            var namespaceName = interceptionMethodSymbol.ContainingNamespace.ToDisplayString();
            var interceptorAttr = interceptionMethodSymbol.GetAttributes().FirstOrDefault(attr =>
                attr.AttributeClass?.ToDisplayString() == $"{Namespace}.{AttributeName}");

            var targetType = interceptorAttr?.AttributeClass?.TypeArguments.FirstOrDefault() ??
                             interceptorAttr?.ConstructorArguments.FirstOrDefault().Value as INamedTypeSymbol;
            if (targetType is null)
            {
                continue;
            }
            
            throw new Exception(string.Join("\n", candidates.Select(t => t.interceptableLocation.ToString())));

            var targets = candidates.Where(candidate =>
            {
                var candidateSemanticModel = compilation.GetSemanticModel(candidate.invocation.SyntaxTree);
                if (candidateSemanticModel.GetSymbolInfo(candidate.invocation).Symbol is not IMethodSymbol
                    candidateMethodSymbol)
                {
                    return false;
                }

                if (candidateMethodSymbol.Arity != interceptionMethodSymbol.Arity)
                {
                    return false;
                }

                if (!SymbolEqualityComparer.IncludeNullability.Equals(candidateMethodSymbol.ContainingType, targetType))
                {
                    return false;
                }
                
                // TODO exclude candidates that are in the same method as the interceptor to avoid self-interception.

                return candidateMethodSymbol.Parameters.Select(t => t.Type)
                    .SequenceEqual(interceptorParameterTypes,
                        SymbolEqualityComparer.IncludeNullability);
            }).ToImmutableArray();

            
        }
//         foreach (var interceptionMethodSyntax in methodDeclarations)
//         {
//             // We need to get semantic model of the class to retrieve metadata.
//             var semanticModel = compilation.GetSemanticModel(interceptionMethodSyntax.SyntaxTree);
//
//             // Symbols allow us to get the compile-time information.
//             var interceptionMethodSymbol =
//                 ModelExtensions.GetDeclaredSymbol(semanticModel, interceptionMethodSyntax) as IMethodSymbol;
//             if (interceptionMethodSymbol == null) continue;
//
//             var namespaceName = interceptionMethodSymbol.ContainingNamespace.ToDisplayString();
//
//             var interceptorAttr = interceptionMethodSymbol.GetAttributes()
//                 .FirstOrDefault(attr => attr.AttributeClass?.ToDisplayString() == $"{Namespace}.{AttributeName}");
//
//             var genericType = interceptorAttr?.AttributeClass?.TypeArguments.FirstOrDefault();
//             var firstArg = interceptorAttr?.ConstructorArguments.FirstOrDefault().Value;
//             var maybeName = interceptorAttr?.ConstructorArguments.ElementAtOrDefault(1).Value as string;
//
//             var fullyQualifiedTypeName = genericType is not null
//                 ? genericType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
//                 : firstArg is INamedTypeSymbol typeSymbol
//                     ? typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
//                     : throw new ArgumentException("Invalid Interceptor attribute arguments");
//
//             var methodName = genericType is not null
//                 ? firstArg as string ?? throw new ArgumentException("Invalid Interceptor attribute arguments")
//                 : maybeName ?? throw new ArgumentException("Invalid Interceptor attribute arguments");
//
//
//             // var genericType = interceptorAttr?.AttributeClass?.TypeArguments.FirstOrDefault();
//             // var typeOrName = interceptorAttr?.ConstructorArguments.FirstOrDefault().Value as string ?? "";
//             // var name = interceptorAttr?.ConstructorArguments.ElementAtOrDefault(1).Value;
//
//             var calls = FindMethodCalls(compilation, fullyQualifiedTypeName, methodName)
//                 .Where(call =>
//                     call.Ancestors().OfType<MethodDeclarationSyntax>().All(m => m != interceptionMethodSyntax));
//
//             // 'Identifier' means the token of the node. Get class name from the syntax node.
//
//             //var methodName = methodSyntax.Identifier.Text;
//             var className = GetContainingClass(interceptionMethodSyntax).Identifier.Text;
//
//             var attributes = calls.Select(invocation =>
//             {
//                 var memberAccessExpressionSyntax = invocation.Expression as MemberAccessExpressionSyntax;
//
//                 //throw new Exception(memberAccessExpressionSyntax.Name.GetLocation().GetLineSpan().StartLinePosition.Character.ToString());
//                 var location = memberAccessExpressionSyntax!.Name.GetLocation();
//
//                 var line = location.GetLineSpan();
//                 var file = line.Path;
//                 return
//                     $"[InterceptsLocation(filePath: \"{file}\", line: {line.StartLinePosition.Line + 1}, column: {line.StartLinePosition.Character + 1})]";
//             });
//
//             var attributesCode = string.Join("\n\t", attributes);
//
//             var code =
//                 $$"""
//                   using System.Runtime.CompilerServices;
//                   namespace {{namespaceName}};
//                   public partial class {{className}}
//                   {
//                       {{attributesCode}}
//                       {{GetMethodSignature(interceptionMethodSyntax)}};
//                   }
//                   """;
//             context.AddSource($"{className}.g.cs", SourceText.From(code, Encoding.UTF8));
//         }
    }

    private IEnumerable<InvocationExpressionSyntax> FindMethodCalls(
        Compilation compilation,
        string fullyQualifiedTypeName,
        string methodName)
    {
        return compilation.SyntaxTrees
            .SelectMany(tree =>
            {
                var semanticModel = compilation.GetSemanticModel(tree);
                return tree.GetRoot()
                    .DescendantNodes()
                    .OfType<InvocationExpressionSyntax>()
                    .Where(invocation =>
                    {
                        var symbol = semanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;

                        return
                            symbol != null
                            && symbol.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                            fullyQualifiedTypeName
                            && symbol.Name == methodName;
                    });
            });
    }

    public static MethodDeclarationSyntax? FindMethodByFullyQualifiedName(Compilation compilation,
        string fullyQualifiedMethodName)
        => compilation.SyntaxTrees
            .SelectMany(tree => tree.GetRoot()
                .DescendantNodes()
                .OfType<MethodDeclarationSyntax>()
                .Select(method => (method,
                    symbol: ModelExtensions.GetDeclaredSymbol(compilation.GetSemanticModel(tree), method) as
                        IMethodSymbol)))
            .FirstOrDefault(tuple =>
                tuple.symbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == fullyQualifiedMethodName)
            .method;

    // public static MethodDeclarationSyntax FindMethodBy(
    //     SemanticModel semanticModel,
    //     INamedTypeSymbol interceptingTypeSymbol,
    //     IMethodSymbol interceptorMethodSymbol)
    // {
    //     var methodDeclarations = interceptingTypeSymbol
    //         .GetMembers(interceptingTypeSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat))
    //         .OfType<IMethodSymbol>()
    //         .Where(s => s.Name == interceptorMethodSymbol.Name);
    //
    //     var targetMethodSymbol =
    //         methodDeclarations.First(m =>
    //             interceptorMethodSymbol.Parameters.Select(t => t.Type).SequenceEqual(m.Parameters.Select(t => t.Type),
    //                 SymbolEqualityComparer.IncludeNullability));
    //
    //
    //     // SymbolFinder.FindReferencesAsync(targetMethodSymbol,).Wait();
    // }

    private static ClassDeclarationSyntax GetContainingClass(MethodDeclarationSyntax methodSyntax)
    {
        return methodSyntax.Ancestors().OfType<ClassDeclarationSyntax>().First();
    }

    private string GetTypeParameters(MethodDeclarationSyntax method)
    {
        if (method.TypeParameterList == null)
            return string.Empty;

        var typeParams = method.TypeParameterList.ToFullString();
        return typeParams;
    }

    // Returns the method signature as a string (e.g., "public static int Foo<T>(int x)")
    private string GetMethodSignature(MethodDeclarationSyntax method)
    {
        var modifiers = string.Join(" ", method.Modifiers.Select(m => m.Text));
        var typeParams = method.TypeParameterList?.ToFullString() ?? "";
        return $"{modifiers} {method.ReturnType} {method.Identifier}{typeParams}{method.ParameterList}".Trim();
    }
}