using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace InterceptorFramework;

[Generator]
public class InterceptorSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "Generators";
    private const string AttributeName = "InterceptorAttribute";

    private const string AttributeSourceCode =
        // lang=CSharp
        $$"""
          // <auto-generated/>
          namespace {{Namespace}}
          {
              [System.AttributeUsage(System.AttributeTargets.Method)]
              public class {{AttributeName}}<T> : System.Attribute
              {
                  public string Value { get; }
                  public {{AttributeName}}(string value) => Value = value;
              }
              
              [System.AttributeUsage(System.AttributeTargets.Method)]
              public class {{AttributeName}} : System.Attribute
              {
                  public string Value { get; }
                  public {{AttributeName}}(System.Type type, string methodName) => Value = methodName;
              }
          }
          namespace System.Runtime.CompilerServices
          {
              [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
              public sealed class InterceptsLocationAttribute(int version, string data) : Attribute;
          }
          """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "ReportAttribute.g.cs",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        var interceptingInvocationsProvider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is InvocationExpressionSyntax
                {
                    Expression: MemberAccessExpressionSyntax
                },
                transform: (GeneratorSyntaxContext context, CancellationToken token) =>
                {
                    var invocation = (InvocationExpressionSyntax)context.Node;
                    var interceptableLocation = context.SemanticModel.GetInterceptableLocation(invocation);
                    if (interceptableLocation is null)
                    {
                        throw new Exception("Bug");
                    }

                    // Extract the opaque 'Data' string from InterceptableLocation
                    var locType = interceptableLocation.GetType();
                    var dataProp = locType.GetProperty("Data", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
                    var data = dataProp?.GetValue(interceptableLocation) as string ?? "";

                    return (invocationExpression: invocation, data);
                })
            .Collect();

        var interceptorDeclarationProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is MethodDeclarationSyntax,
                (ctx, _) => GetMethodForSourceGen(ctx))
            .Where(t => t.attributeFound)
            .Select((t, _) => (t.method, t.targetType, t.methodName))
            .Combine(interceptingInvocationsProvider)
            .Select((t, _) =>
            {
                var ((interceptor, targetType, targetMethodName), interceptions) = t;
                var candidates = interceptions
                    .Where(i =>
                    {
                        var access = (MemberAccessExpressionSyntax)i.invocationExpression.Expression;
                        return access.Name.Identifier.Text == targetMethodName;
                    })
                    .ToImmutableArray();
                return (interceptor, targetType, targetMethodName, candidates);
            });


        context.RegisterSourceOutput(context.CompilationProvider.Combine(interceptorDeclarationProvider.Collect()),
            (ctx, t) => GenerateCode(ctx, t.Left, t.Right));
    }

    private (MethodDeclarationSyntax method, bool attributeFound, INamedTypeSymbol? targetType, string? methodName) GetMethodForSourceGen(GeneratorSyntaxContext context)
    {
        var methodDeclarationSyntax = (MethodDeclarationSyntax)context.Node;

        // Go through all attributes of the class.
        foreach (AttributeListSyntax attributeListSyntax in methodDeclarationSyntax.AttributeLists)
        foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                continue; // if we can't get the symbol, ignore it

            string attributeName = attributeSymbol.ContainingType.ToDisplayString();

            // Check the full name of the [Interceptor] attribute.
            if (attributeName.StartsWith($"{Namespace}.{AttributeName}"))
            {
                var attrData = context.SemanticModel.GetDeclaredSymbol(methodDeclarationSyntax)?
                    .GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString().StartsWith($"{Namespace}.{AttributeName}") == true);

                if (attrData is null) continue;

                INamedTypeSymbol? targetType = null;
                string? methodName = null;

                if (attrData.AttributeClass?.IsGenericType == true)
                {
                    targetType = attrData.AttributeClass.TypeArguments.FirstOrDefault() as INamedTypeSymbol;
                    methodName = attrData.ConstructorArguments.FirstOrDefault().Value as string;
                }
                else if (attrData.ConstructorArguments.Length >= 2)
                {
                    targetType = attrData.ConstructorArguments[0].Value as INamedTypeSymbol;
                    methodName = attrData.ConstructorArguments[1].Value as string;
                }

                if (targetType is not null && methodName is not null)
                {
                    return (methodDeclarationSyntax, true, targetType, methodName);
                }
            }
        }

        return (methodDeclarationSyntax, false, null, null);
    }

    private void GenerateCode(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<(MethodDeclarationSyntax interceptor, INamedTypeSymbol targetType, string targetMethodName, ImmutableArray<(InvocationExpressionSyntax invocationExpression, string data)> candidates)> interceptorMethods)
    {
        foreach (var (interceptor, targetType, targetMethodName, candidates) in interceptorMethods)
        {
            var semanticModel = compilation.GetSemanticModel(interceptor.SyntaxTree);

            if (ModelExtensions.GetDeclaredSymbol(semanticModel, interceptor) is not IMethodSymbol interceptionMethodSymbol)
            {
                continue;
            }

            var interceptorParameterTypes = interceptionMethodSymbol.Parameters.Select(t => t.Type).ToImmutableArray();
            var namespaceName = interceptionMethodSymbol.ContainingNamespace.ToDisplayString();
            var className = GetContainingClass(interceptor).Identifier.Text;

            var targets = candidates.Where(candidate =>
            {
                var candidateSemanticModel = compilation.GetSemanticModel(candidate.invocationExpression.SyntaxTree);
                if (candidateSemanticModel.GetSymbolInfo(candidate.invocationExpression).Symbol is not IMethodSymbol candidateMethodSymbol)
                {
                    return false;
                }

                if (candidateMethodSymbol.Name != targetMethodName)
                {
                    return false;
                }

                if (candidateMethodSymbol.Arity != interceptionMethodSymbol.Arity)
                {
                    return false;
                }

                if (!SymbolEqualityComparer.IncludeNullability.Equals(candidateMethodSymbol.ContainingType, targetType))
                {
                    return false;
                }

                // Recursion protection: exclude calls that are within the interceptor method's own body
                if (candidate.invocationExpression.SyntaxTree == interceptor.SyntaxTree &&
                    interceptor.Body?.Span.Contains(candidate.invocationExpression.Span) == true)
                {
                    return false;
                }

                return candidateMethodSymbol.Parameters.Select(t => t.Type)
                    .SequenceEqual(interceptorParameterTypes, SymbolEqualityComparer.IncludeNullability);
            }).ToImmutableArray();

            if (targets.Length == 0)
            {
                continue;
            }

            var attributesCode = string.Join("\n    ", targets.Select(t =>
            {
                return $"[InterceptsLocation(version: 1, data: \"{t.data}\")]";
            }));

            var code =
                $$"""
                  // <auto-generated/>
                  #nullable enable
                  using System.Runtime.CompilerServices;
                  namespace {{namespaceName}};
                  public partial class {{className}}
                  {
                      {{attributesCode}}
                      {{GetMethodSignature(interceptor)}};
                  }
                  """;

            context.AddSource($"{namespaceName}.{className}.{interceptor.Identifier.Text}.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }

    private static ClassDeclarationSyntax GetContainingClass(MethodDeclarationSyntax methodSyntax)
    {
        return methodSyntax.Ancestors().OfType<ClassDeclarationSyntax>().First();
    }

    // Returns the method signature as a string (e.g., "public static partial int Foo<T>(int x)")
    private string GetMethodSignature(MethodDeclarationSyntax method)
    {
        var modifiers = method.Modifiers.Select(m => m.Text).ToList();
        if (!modifiers.Contains("partial"))
        {
            // The 'partial' modifier must appear after other modifiers (like public static) but before the return type
            modifiers.Add("partial");
        }
        var modifiersString = string.Join(" ", modifiers);
        var typeParams = method.TypeParameterList?.ToFullString() ?? "";
        return $"{modifiersString} {method.ReturnType} {method.Identifier}{typeParams}{method.ParameterList}".Trim();
    }
}