using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Splice;

[Generator]
public class InterceptorSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "Generators";
    private const string AttributeName = "InterceptorAttribute";

    private const string AttributeSourceCode =
        // lang=CSharp
        $$"""
          // <auto-generated/>
          namespace {{Namespace}}
          {
              [System.AttributeUsage(System.AttributeTargets.Method)]
              public class {{AttributeName}}<T> : System.Attribute
              {
                  public string Value { get; }
                  public {{AttributeName}}(string value) => Value = value;
              }
              
              [System.AttributeUsage(System.AttributeTargets.Method)]
              public class {{AttributeName}} : System.Attribute
              {
                  public string Value { get; }
                  public {{AttributeName}}(System.Type type, string methodName) => Value = methodName;
              }
          }
          namespace System.Runtime.CompilerServices
          {
              [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
              public sealed class InterceptsLocationAttribute(int version, string data) : Attribute;
          }
          """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => {
            ctx.AddSource(
                "ReportAttribute.g.cs",
                SourceText.From(AttributeSourceCode, Encoding.UTF8));
        });

        var interceptingInvocationsProvider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is InvocationExpressionSyntax,
                transform: (GeneratorSyntaxContext context, CancellationToken token) =>
                {
                    var invocation = (InvocationExpressionSyntax)context.Node;
                    var semanticModel = context.SemanticModel;
                    var symbolInfo = semanticModel.GetSymbolInfo(invocation);
                    var methodSymbol = symbolInfo.Symbol as IMethodSymbol;

                    if (methodSymbol is null && symbolInfo.CandidateSymbols.Length > 0)
                    {
                        methodSymbol = symbolInfo.CandidateSymbols[0] as IMethodSymbol;
                    }

                    if (methodSymbol is null)
                    {
                         return (invocationExpression: invocation, data: (string?)null, methodSymbol: (IMethodSymbol?)null);
                    }

                    // For generic class methods, we need the original definition to match correctly
                    if (methodSymbol.IsGenericMethod)
                    {
                        methodSymbol = methodSymbol.OriginalDefinition;
                    }
                    else if (methodSymbol.ContainingType.IsGenericType)
                    {
                        // This handles non-generic methods in generic classes
                        // We want the method symbol from the open generic type
                        var originalType = methodSymbol.ContainingType.OriginalDefinition;
                        methodSymbol = originalType.GetMembers(methodSymbol.Name).OfType<IMethodSymbol>().FirstOrDefault(m => m.Parameters.Length == methodSymbol.Parameters.Length);
                    }

                    var interceptableLocation = semanticModel.GetInterceptableLocation(invocation);
                    if (interceptableLocation is null)
                    {
                        return (invocationExpression: invocation, data: (string?)null, methodSymbol: (IMethodSymbol?)null);
                    }

                    // Extract the opaque 'Data' string from InterceptableLocation
                    var locType = interceptableLocation.GetType();
                    var dataProp = locType.GetProperty("Data", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
                    var data = dataProp?.GetValue(interceptableLocation) as string ?? "";

                    return (invocationExpression: invocation, data: (string?)data, methodSymbol);
                })
            .Where(t => t.data is not null && t.methodSymbol is not null)
            .Collect();

        var interceptorDeclarationProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is MethodDeclarationSyntax,
                (ctx, _) => GetMethodForSourceGen(ctx))
            .Where(t => t.attributeFound)
            .Select((t, _) => (t.method, t.targetType, t.methodName));

        var combinedProvider = interceptorDeclarationProvider
            .Combine(interceptingInvocationsProvider)
            .Select((t, _) =>
            {
                var ((interceptor, targetType, targetMethodName), interceptions) = t;
                var candidates = interceptions
                    .Select(i => (i.invocationExpression, i.data!, (IMethodSymbol?)i.methodSymbol))
                    .ToImmutableArray();
                return (interceptor, targetType, targetMethodName, candidates);
            });

        context.RegisterSourceOutput(context.CompilationProvider.Combine(combinedProvider.Collect()),
            (ctx, t) => GenerateCode(ctx, t.Left, t.Right));
    }

    private (MethodDeclarationSyntax method, bool attributeFound, INamedTypeSymbol? targetType, string? methodName) GetMethodForSourceGen(GeneratorSyntaxContext context)
    {
        var methodDeclarationSyntax = (MethodDeclarationSyntax)context.Node;
        var methodSymbol = context.SemanticModel.GetDeclaredSymbol(methodDeclarationSyntax);
        if (methodSymbol == null) return (methodDeclarationSyntax, false, null, null);

        // Validation: Interceptors cannot be declared in generic types at any level of nesting.
        var containingType = methodSymbol.ContainingType;
        while (containingType != null)
        {
            if (containingType.IsGenericType)
            {
                // We should ideally report a diagnostic here, but for now we'll just skip it
                // and maybe log it or rely on the fact that it won't match targets.
                return (methodDeclarationSyntax, false, null, null);
            }
            containingType = containingType.ContainingType;
        }

        // Go through all attributes of the class.
        foreach (var attrData in methodSymbol.GetAttributes())
        {
            var attributeClass = attrData.AttributeClass;
            if (attributeClass == null) continue;

            string attributeName = attributeClass.ToDisplayString();
            
            // Check the full name of the [Interceptor] attribute.
            if (attributeName.StartsWith($"{Namespace}.{AttributeName}"))
            {
                INamedTypeSymbol? targetType = null;
                string? methodName = null;

                if (attributeClass.IsGenericType)
                {
                    targetType = attributeClass.TypeArguments.FirstOrDefault() as INamedTypeSymbol;
                    methodName = attrData.ConstructorArguments.FirstOrDefault().Value as string;
                }
                else if (attrData.ConstructorArguments.Length >= 2)
                {
                    targetType = attrData.ConstructorArguments[0].Value as INamedTypeSymbol;
                    methodName = attrData.ConstructorArguments[1].Value as string;
                }

                if (targetType is not null && methodName is not null)
                {
                    return (methodDeclarationSyntax, true, targetType, methodName);
                }
            }
        }

        return (methodDeclarationSyntax, false, null, null);
    }

    private void GenerateCode(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<(MethodDeclarationSyntax interceptor, INamedTypeSymbol? targetType, string? targetMethodName, ImmutableArray<(InvocationExpressionSyntax invocationExpression, string data, IMethodSymbol? methodSymbol)> candidates)> interceptorMethods)
    {
        foreach (var (interceptor, targetType, targetMethodName, candidates) in interceptorMethods)
        {
            if (targetType is null || targetMethodName is null) continue;
            var semanticModel = compilation.GetSemanticModel(interceptor.SyntaxTree);

            if (ModelExtensions.GetDeclaredSymbol(semanticModel, interceptor) is not IMethodSymbol interceptionMethodSymbol)
            {
                continue;
            }

            var interceptorParameterTypes = interceptionMethodSymbol.Parameters.Select(t => t.Type).ToImmutableArray();
            var namespaceName = interceptionMethodSymbol.ContainingNamespace.ToDisplayString();
            var className = GetContainingClass(interceptor).Identifier.Text;

            var targets = candidates.Where(candidate =>
            {
                var targetMethod = candidate.Item3; 
                if (targetMethod is null) return false;
                
                var originalTargetMethod = targetMethod.IsGenericMethod ? targetMethod.OriginalDefinition : targetMethod;

                if (originalTargetMethod.Name != targetMethodName) return false;
                
                // Compare containing types using SymbolEqualityComparer and OriginalDefinition to handle generic classes
                if (!SymbolEqualityComparer.Default.Equals(originalTargetMethod.ContainingType.OriginalDefinition, targetType.OriginalDefinition)) return false;
                
                // Arity check: interceptor arity must be 0 OR equal to the sum of containing type arities and method arity
                int requiredArity = GetRequiredArity(originalTargetMethod);
                if (interceptionMethodSymbol.Arity != 0 && interceptionMethodSymbol.Arity != requiredArity) return false;

                // Recursion protection: exclude calls that are within the interceptor method's own body
                if (candidate.invocationExpression.SyntaxTree == interceptor.SyntaxTree &&
                    interceptor.Body?.Span.Contains(candidate.invocationExpression.Span) == true)
                {
                    return false;
                }

                var targetParamTypes = originalTargetMethod.Parameters.Select(t => t.Type).ToImmutableArray();
                var interceptorParamTypes = interceptionMethodSymbol.Parameters.Select(t => t.Type).ToImmutableArray();

                // If the interceptor is an extension method, we need to handle the 'this' parameter
                int interceptorParamOffset = interceptionMethodSymbol.IsExtensionMethod ? 1 : 0;

                if (targetParamTypes.Length != (interceptorParamTypes.Length - interceptorParamOffset)) return false;

                var allTargetTypeParameters = GetAllTypeParameters(originalTargetMethod);

                for (int i = 0; i < targetParamTypes.Length; i++)
                {
                    var targetParam = targetParamTypes[i];
                    var interceptorParam = interceptorParamTypes[i + interceptorParamOffset];

                    if (!IsTypeCompatible(targetParam, interceptorParam, allTargetTypeParameters, interceptionMethodSymbol.TypeParameters))
                    {
                        return false;
                    }
                }

                return true;
            }).ToImmutableArray();

            if (targets.Length == 0)
            {
                continue;
            }

            var attributesCode = string.Join("\n    ", targets.Select(t =>
            {
                return $"[InterceptsLocation(version: 1, data: \"{t.data}\")]";
            }));

            var code =
                $$"""
                  // <auto-generated/>
                  #nullable enable
                  using System.Runtime.CompilerServices;
                  namespace {{namespaceName}};
                  public partial class {{className}}
                  {
                      {{attributesCode}}
                      {{GetMethodSignature(interceptor)}};
                  }
                  """;

            context.AddSource($"{namespaceName}.{className}.{interceptor.Identifier.Text}.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }

    private static int GetRequiredArity(IMethodSymbol method)
    {
        int arity = method.Arity;
        var type = method.ContainingType;
        while (type != null)
        {
            arity += type.Arity;
            type = type.ContainingType;
        }
        return arity;
    }

    private static ImmutableArray<ITypeParameterSymbol> GetAllTypeParameters(IMethodSymbol method)
    {
        var builder = ImmutableArray.CreateBuilder<ITypeParameterSymbol>();
        var type = method.ContainingType;
        var types = new List<INamedTypeSymbol>();
        while (type != null)
        {
            types.Add(type);
            type = type.ContainingType;
        }
        types.Reverse();
        foreach (var t in types)
        {
            builder.AddRange(t.TypeParameters);
        }
        builder.AddRange(method.TypeParameters);
        return builder.ToImmutable();
    }

    private static bool IsTypeCompatible(ITypeSymbol targetType, ITypeSymbol interceptorType, ImmutableArray<ITypeParameterSymbol> allTargetTypeParameters, ImmutableArray<ITypeParameterSymbol> interceptorTypeParameters)
    {
        if (targetType.Kind == SymbolKind.TypeParameter)
        {
            if (interceptorType.Kind != SymbolKind.TypeParameter) return false;

            var targetTp = (ITypeParameterSymbol)targetType;
            var interceptorTp = (ITypeParameterSymbol)interceptorType;

            int targetIndex = allTargetTypeParameters.IndexOf(targetTp, SymbolEqualityComparer.Default);
            int interceptorIndex = interceptorTypeParameters.IndexOf(interceptorTp, SymbolEqualityComparer.Default);

            return targetIndex == interceptorIndex && targetIndex != -1;
        }

        if (targetType is INamedTypeSymbol targetNamed && interceptorType is INamedTypeSymbol interceptorNamed)
        {
            if (!SymbolEqualityComparer.Default.Equals(targetNamed.OriginalDefinition, interceptorNamed.OriginalDefinition)) return false;
            if (targetNamed.TypeArguments.Length != interceptorNamed.TypeArguments.Length) return false;

            for (int i = 0; i < targetNamed.TypeArguments.Length; i++)
            {
                if (!IsTypeCompatible(targetNamed.TypeArguments[i], interceptorNamed.TypeArguments[i], allTargetTypeParameters, interceptorTypeParameters))
                {
                    return false;
                }
            }
            return true;
        }

        return SymbolEqualityComparer.Default.Equals(targetType, interceptorType);
    }

    private static ClassDeclarationSyntax GetContainingClass(MethodDeclarationSyntax methodSyntax)
    {
        return methodSyntax.Ancestors().OfType<ClassDeclarationSyntax>().First();
    }

    private string GetMethodSignature(MethodDeclarationSyntax method)
    {
        var modifiers = method.Modifiers.Select(m => m.Text).ToList();
        if (!modifiers.Contains("partial"))
        {
            // The 'partial' modifier must appear after other modifiers (like public static) but before the return type
            modifiers.Add("partial");
        }
        var modifiersString = string.Join(" ", modifiers);
        var typeParams = method.TypeParameterList?.ToString().Trim() ?? "";
        
        // Always include all parameters for the partial declaration
        var parameters = method.ParameterList.Parameters;
        var filteredParameters = parameters.Select(p => p.ToString().Trim());
        var parameterList = "(" + string.Join(", ", filteredParameters) + ")";

        var constraints = string.Join(" ", method.ConstraintClauses.Select(c => c.ToString().Trim())).Trim();
        
        return $"{modifiersString} {method.ReturnType.ToString().Trim()} {method.Identifier.Text.Trim()}{typeParams}{parameterList} {constraints}".Trim();
    }
}
